version: "3.8"
services:
  market_server:
    build: ./server
    ports:
      - "50051:50051"
    volumes:
      - ./shared:/shared

  analytics_server:
    build: ./server
    ports:
      - "50052:50052"

  web:
    build: ./client/web
    ports:
      - "5000:5000"

  admin_ssh:
    build: ./admin
    ports:
      - "2222:22"
    volumes:
      - ./shared:/shared
